/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oracle.alura.conversordemoneda.gui;

/**
 *
 * @author Brayan Legarda Villegas
 */
public class PantallaConversorDeMedidasLongitud extends javax.swing.JFrame {

    /**
     * Creates new form PantallaConversorDeMedidasLongitud
     */
    public PantallaConversorDeMedidasLongitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jComboBoxMedidas = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAreaResultado = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        txtAdvertencia = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpanel.setBackground(new java.awt.Color(204, 204, 255));

        jComboBoxMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulgadas a milimetros", "Yardas a metros", "Millas a kilometros" }));
        jComboBoxMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtTitulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 255));
        txtTitulo.setText("Conversor mededias de longitud");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Longitud");

        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLongitudKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Resultado");

        txtAreaResultado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnConvertir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvertir.setEnabled(false);
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        btnConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnConvertirKeyReleased(evt);
            }
        });

        txtAdvertencia.setForeground(new java.awt.Color(255, 0, 0));

        btnAtras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAtras.setText("Volver");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLongitud))
                                    .addGroup(jpanelLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtAreaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnConvertir)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAreaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudActionPerformed

    
    public void habilitarBoton_f(){
        if(!txtLongitud.getText().isEmpty()){
            btnConvertir.setEnabled(true);
        }else{
            btnConvertir.setEnabled(false);
        }
    }
    
    public String ObtnerTipoopcion_f(String opc){
    
        String opcion;
        switch (opc) {
            
            case "Pulgadas a milimetros" -> opcion = "1";
            case "Yardas a metros" -> opcion = "2";
            case "Millas a kilometros" -> opcion = "3";
            default -> throw new AssertionError();
        }
         return opcion;
    }

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
       
        double quantity = Double.parseDouble(txtLongitud.getText());
        double milimetros=0;
        double metros=0;
        double kilometros=0;
        
        String opcion = jComboBoxMedidas.getSelectedItem().toString();
        
        opcion = ObtnerTipoopcion_f(opcion);
        
        switch (opcion) {
            case "1" -> {
                milimetros = quantity * 25.4;
                txtAreaResultado.setText(quantity +" Pulgadas equivalen a " + milimetros+ " milimetros");
            }
                
            case "2" -> {
                metros = quantity * 0.9144;
                txtAreaResultado.setText(quantity +" Yardas equivalen a " + metros+ " metros");
            }
               
            case "3" -> {
                kilometros = quantity * 1.6093;
                txtAreaResultado.setText(quantity +" Millas equivalen a " + kilometros+ " Kilometros");
            }
                
            default -> throw new AssertionError();
        } 
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnConvertirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvertirKeyReleased
      
    }//GEN-LAST:event_btnConvertirKeyReleased

    private void txtLongitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyReleased
          if(!"".equals(txtLongitud.getText())){
            txtAreaResultado.setText("");
        
        }
        
        habilitarBoton_f();
    }//GEN-LAST:event_txtLongitudKeyReleased

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean borrrar = key == 8;
        boolean punto = key == 46;

        if (!numeros && !borrrar && !punto) {
            evt.consume();
            txtAdvertencia.setText("Solo se permiten Números");
        } else {
            txtAdvertencia.setText("");  
        }
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        PantallaPrincipal pantalla = new PantallaPrincipal();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> jComboBoxMedidas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel txtAdvertencia;
    private javax.swing.JLabel txtAreaResultado;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
